#!/usr/bin/env bash
# One-shot VM bootstrap for the VectorForge public deployment (Ubuntu 22.04 / 24.04).
#
# Usage on the server, from the unpacked bundle root:
#     bash webapp/deploy/setup-vm.sh
#
# It (1) installs Docker if missing, (2) creates webapp/deploy/.env interactively the first time
# (domain, basic-auth user + password hash, optional spend keys), then (3) builds + launches the app
# behind Caddy. Re-running it just rebuilds/relaunches with the existing .env. Secrets live ONLY in
# .env on the server; nothing is committed or transmitted anywhere.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"     # webapp/deploy
ROOT="$(cd "$HERE/../.." && pwd)"                          # bundle root == Docker build context
ENV_FILE="$HERE/.env"
COMPOSE="$HERE/docker-compose.yml"
DOMAIN_DEFAULT="lab.abdullahalghamdi.com"

echo "==> VectorForge VM bootstrap"
echo "    build context: $ROOT"

# ---------------------------------------------------------------- 1) Docker
if ! command -v docker >/dev/null 2>&1; then
  echo "==> Installing Docker (get.docker.com)..."
  curl -fsSL https://get.docker.com | sh
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "ERROR: the 'docker compose' plugin is not available." >&2
  echo "       On Ubuntu: apt-get update && apt-get install -y docker-compose-plugin" >&2
  exit 1
fi

# ---------------------------------------------------------------- 2) .env (first run only)
if [ ! -f "$ENV_FILE" ]; then
  echo "==> First run: creating $ENV_FILE"
  read -rp "    Public hostname [$DOMAIN_DEFAULT]: " DOM; DOM="${DOM:-$DOMAIN_DEFAULT}"
  read -rp "    Basic-auth username [admin]: " BUSER; BUSER="${BUSER:-admin}"
  while :; do
    read -rsp "    Choose a site password: " PW1; echo
    read -rsp "    Repeat the password:    " PW2; echo
    [ -n "$PW1" ] && [ "$PW1" = "$PW2" ] && break
    echo "    Passwords empty or did not match. Try again."
  done
  echo "==> Hashing the password with Caddy..."
  HASH="$(docker run --rm caddy:2 caddy hash-password --plaintext "$PW1")"
  HASH_ESC="${HASH//\$/\$\$}"            # escape $ -> $$ so docker compose does not interpolate it

  echo "    Optional spend keys (press Enter to skip; that lane stays a free local fallback):"
  read -rp "    ANTHROPIC_API_KEY: " AK || true
  read -rp "    RUNPOD_API_KEY:    " RK || true
  read -rp "    RUNPOD_ENDPOINT_ID: " RE || true

  umask 077                              # .env is readable only by its owner
  cat > "$ENV_FILE" <<EOF
# Generated by setup-vm.sh -- holds secrets, never commit. Edit + re-run setup-vm.sh to apply changes.
VF_DOMAIN=$DOM
VF_BASIC_USER=$BUSER
VF_BASIC_HASH=$HASH_ESC

ANTHROPIC_API_KEY=$AK
RUNPOD_API_KEY=$RK
RUNPOD_ENDPOINT_ID=$RE

# hard per-UTC-day spend backstop (a leaked password cannot exceed these)
VF_DAILY_USD_CAP=5.0
VF_MAX_GPU_RUNS_PER_DAY=100
VF_MAX_LLM_CALLS_PER_DAY=200
VF_GPU_USD_PER_RUN=0.05
VF_LLM_USD_PER_CALL=0.02
EOF
  echo "==> Wrote $ENV_FILE (domain=$DOM, user=$BUSER)"
else
  echo "==> Using existing $ENV_FILE"
fi

# ---------------------------------------------------------------- 3) build + launch
echo "==> Building + launching (this pulls images + builds on first run)..."
cd "$ROOT"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE" up -d --build

DOM_NOW="$(grep -E '^VF_DOMAIN=' "$ENV_FILE" | cut -d= -f2-)"
echo
echo "==> Up. Caddy is fetching a TLS cert for https://$DOM_NOW (needs the DNS A record live + ports 80/443 open)."
echo "    Status : docker compose -f $COMPOSE ps"
echo "    Logs   : docker compose -f $COMPOSE logs -f caddy"
echo "    Health : curl -u $BUSER:'<password>' https://$DOM_NOW/healthz"
echo "    Open   : https://$DOM_NOW   (enter the username + password you set)"
