"""Enhanced program representation with hypothesis, lineage, and risk profile.

A Program is more than a code string — it's a structured scientific object:
  - hypothesis: WHY we think this will work
  - parent_id: what it was derived from (mutation lineage)
  - derivation: typed derivation method (mutation, diagnosis, literature, ensemble, etc.)
  - recipe: structured description of the approach
  - expected_improvement: what we expect to gain
  - cost_estimate: predicted wall-clock seconds
  - risk_profile: how risky/novel this approach is

The lineage tree enables:
  - Tracing the ancestry of winning solutions
  - Learning which derivation paths are productive
  - Cross-experiment knowledge transfer (which lineages generalize)
  - Understanding WHY something worked, not just THAT it worked
"""
from __future__ import annotations

import hashlib
import json
import os
import time
from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


class DerivationType(str, Enum):
    """How a program was derived from its parent (or created fresh)."""
    SEED = "seed"                           # initial baseline from catalog
    MUTATE_HYPERPARAMS = "mutate_hyperparams"  # same model, different hyperparams
    MUTATE_FEATURES = "mutate_features"     # different feature engineering
    MUTATE_PREPROCESSING = "mutate_preprocessing"  # different preprocessing
    DIAGNOSE_IMPROVE = "diagnose_improve"   # derived from diagnosis of a failure
    LITERATURE_INSPIRED = "literature_inspired"  # from paper/arxiv retrieval
    LLM_GENERATED = "llm_generated"         # directly generated by LLM
    ENSEMBLE = "ensemble"                    # combination of multiple parents
    DATA_TRANSFORM = "data_transform"       # derived by changing data representation
    ARCHITECTURE_SEARCH = "architecture_search"  # neural architecture search
    CROSS_TASK_TRANSFER = "cross_task_transfer"  # transferred from another task
    SELF_IMPROVEMENT = "self_improvement"    # system improved its own prompt/approach
    RETRIEVAL = "retrieval"                  # retrieved from knowledge base
    MANUAL = "manual"                        # manually specified


class RiskProfile(str, Enum):
    """How risky/novel this program is."""
    SAFE_INCREMENTAL = "safe_incremental"     # small change from proven approach
    MODERATE_EXPLORATION = "moderate_exploration"  # reasonable variation
    HIGH_VARIANCE = "high_variance"           # novel approach, might fail
    NOVEL_ARCHITECTURE = "novel_architecture"  # completely new architecture
    EXPERIMENTAL = "experimental"             # untested idea, high risk


@dataclass
class EnhancedProgram:
    """A structured scientific program — the unit of research.

    Beyond just code, captures the full scientific context:
    what we hypothesize, how we derived it, what we expect.
    """
    # Core
    code: str                              # the executable code
    source: str                            # "seed" | "mutation" | "llm" | "retrieval" | ...
    label: str = ""                        # human-readable short name

    # Scientific context
    hypothesis: str = ""                   # WHY we think this will work
    expected_improvement: str = ""         # what gain we expect (free text)
    expected_improvement_pct: float = 0.0  # estimated % improvement over parent

    # Lineage
    parent_id: Optional[str] = None        # what program this was derived from
    derivation: DerivationType = DerivationType.LLM_GENERATED
    generation: int = 0                    # depth in derivation tree (0=seed)

    # Structure
    recipe: Dict[str, Any] = field(default_factory=dict)
    # recipe example: {"base_model": "GradientBoosting", "features": ["pca_5", "poly_2"],
    #                  "preprocessing": ["StandardScaler", "SMOTE"], "target_transform": None}

    # Cost and risk
    cost_estimate_s: float = 0.0           # predicted wall-clock seconds
    risk_profile: RiskProfile = RiskProfile.MODERATE_EXPLORATION

    # Provenance
    provenance: Dict[str, Any] = field(default_factory=dict)
    # provenance example: {"arxiv_ids": ["2301.12345"], "prompt_hash": "abc123",
    #                       "retrieval_similarity": 0.87}

    # Metadata
    created_at: float = field(default_factory=time.time)
    attempt_id: Optional[str] = None       # which strategy loop attempt created this

    @property
    def id(self) -> str:
        """Content-addressed ID from code hash."""
        h = hashlib.sha256(self.code.encode("utf-8")).hexdigest()[:12]
        return f"{self.source}:{self.label or 'prog'}:{h}"

    @property
    def ancestry_depth(self) -> int:
        """How many derivation steps from a seed."""
        return self.generation

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dict for JSON storage."""
        d = asdict(self)
        d["derivation"] = self.derivation.value
        d["risk_profile"] = self.risk_profile.value
        d["id"] = self.id
        return d

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "EnhancedProgram":
        """Deserialize from dict."""
        d = dict(d)
        d.pop("id", None)
        if "derivation" in d and isinstance(d["derivation"], str):
            d["derivation"] = DerivationType(d["derivation"])
        if "risk_profile" in d and isinstance(d["risk_profile"], str):
            d["risk_profile"] = RiskProfile(d["risk_profile"])
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

    @classmethod
    def from_frontier_program(cls, prog: Any) -> "EnhancedProgram":
        """Create from a frontier.program.Program instance."""
        return cls(
            code=getattr(prog, "code", ""),
            source=getattr(prog, "source", "unknown"),
            label=getattr(prog, "label", ""),
            parent_id=getattr(prog, "parent_id", None),
            provenance=getattr(prog, "provenance", {}),
            derivation=DerivationType.LLM_GENERATED if getattr(prog, "source", "") == "llm"
                else DerivationType.SEED if getattr(prog, "source", "") == "seed"
                else DerivationType.RETRIEVAL if getattr(prog, "source", "") == "retrieval"
                else DerivationType.MUTATE_HYPERPARAMS,
        )

    def __repr__(self) -> str:
        return f"EnhancedProgram({self.id}, hyp='{self.hypothesis[:40]}...')"


@dataclass
class ProgramLineage:
    """A derivation tree of programs — traces the full ancestry of a solution."""
    programs: Dict[str, EnhancedProgram] = field(default_factory=dict)

    def add(self, program: EnhancedProgram) -> None:
        """Add a program to the lineage tree."""
        self.programs[program.id] = program

    def get_ancestors(self, program_id: str) -> List[EnhancedProgram]:
        """Get the full ancestry chain for a program (cycle-safe)."""
        chain = []
        seen = set()
        current = self.programs.get(program_id)
        while current is not None and current.id not in seen:
            seen.add(current.id)
            chain.append(current)
            if current.parent_id is None:
                break
            current = self.programs.get(current.parent_id)
        return chain

    def get_children(self, program_id: str) -> List[EnhancedProgram]:
        """Get direct children of a program."""
        return [p for p in self.programs.values() if p.parent_id == program_id]

    def get_seeds(self) -> List[EnhancedProgram]:
        """Get all root/seed programs (no parent)."""
        return [p for p in self.programs.values() if p.parent_id is None]

    def derivation_stats(self) -> Dict[str, int]:
        """Count programs by derivation type."""
        stats: Dict[str, int] = {}
        for p in self.programs.values():
            key = p.derivation.value
            stats[key] = stats.get(key, 0) + 1
        return stats

    def productive_derivations(self, score_fn) -> Dict[str, float]:
        """Which derivation types produce higher-scoring programs?

        Args:
            score_fn: callable(program_id) -> float score, or None if not evaluated
        """
        scores_by_type: Dict[str, List[float]] = {}
        for p in self.programs.values():
            score = score_fn(p.id)
            if score is not None:
                key = p.derivation.value
                if key not in scores_by_type:
                    scores_by_type[key] = []
                scores_by_type[key].append(score)
        return {k: sum(v) / len(v) for k, v in scores_by_type.items() if v}


class ProgramRegistry:
    """Persistent registry of all programs across experiments.

    Enables cross-experiment knowledge transfer:
    - "What program structures have worked on similar tasks?"
    - "Which derivation paths lead to good solutions?"
    - "What hypotheses have been tested and confirmed/refuted?"
    """

    def __init__(self, persist_path: Optional[str] = None):
        if persist_path is None:
            persist_path = os.path.expanduser("~/.attestra/program_registry.jsonl")
        self._path = persist_path
        os.makedirs(os.path.dirname(self._path), exist_ok=True)

    def record(self, program: EnhancedProgram, score: Optional[float] = None,
               certified: bool = False, task_fingerprint: str = "") -> None:
        """Record a program and its outcome."""
        entry = program.to_dict()
        entry["outcome_score"] = score
        entry["outcome_certified"] = certified
        entry["task_fingerprint"] = task_fingerprint
        entry["recorded_at"] = time.time()
        with open(self._path, "a") as f:
            f.write(json.dumps(entry, default=str) + "\n")

    def retrieve_similar(self, hypothesis: str = "", recipe: Optional[Dict] = None,
                         task_fingerprint: str = "", limit: int = 10) -> List[Dict]:
        """Retrieve programs similar to a query.

        Similarity is based on:
        - Hypothesis text overlap (keyword match)
        - Recipe structure overlap
        - Task fingerprint match
        """
        if not os.path.exists(self._path):
            return []

        entries = []
        with open(self._path, "r") as f:
            for line in f:
                try:
                    entries.append(json.loads(line.strip()))
                except (json.JSONDecodeError, ValueError):
                    continue

        if not entries:
            return []

        # Score each entry for similarity
        scored = []
        hyp_words = set(hypothesis.lower().split()) if hypothesis else set()
        recipe_keys = set(recipe.keys()) if recipe else set()

        for entry in entries:
            score = 0.0
            # Task fingerprint exact match (strongest signal)
            if task_fingerprint and entry.get("task_fingerprint") == task_fingerprint:
                score += 5.0
            # Hypothesis word overlap
            entry_hyp_words = set(entry.get("hypothesis", "").lower().split())
            if hyp_words and entry_hyp_words:
                overlap = len(hyp_words & entry_hyp_words) / max(len(hyp_words), 1)
                score += overlap * 3.0
            # Recipe structure overlap
            entry_recipe = entry.get("recipe", {})
            if recipe_keys and entry_recipe:
                recipe_overlap = len(recipe_keys & set(entry_recipe.keys())) / max(len(recipe_keys), 1)
                score += recipe_overlap * 2.0
            # Bonus for certified programs
            if entry.get("outcome_certified"):
                score += 1.0
            scored.append((score, entry))

        scored.sort(key=lambda x: x[0], reverse=True)
        return [entry for _, entry in scored[:limit] if _ > 0]

    def get_productive_derivations(self, task_type: str = "") -> Dict[str, float]:
        """Which derivation types have highest average scores?"""
        if not os.path.exists(self._path):
            return {}

        scores_by_type: Dict[str, List[float]] = {}
        with open(self._path, "r") as f:
            for line in f:
                try:
                    entry = json.loads(line.strip())
                    if entry.get("outcome_score") is not None:
                        dt = entry.get("derivation", "unknown")
                        if dt not in scores_by_type:
                            scores_by_type[dt] = []
                        scores_by_type[dt].append(entry["outcome_score"])
                except (json.JSONDecodeError, ValueError):
                    continue

        return {k: sum(v) / len(v) for k, v in scores_by_type.items() if v}

    def summary(self) -> Dict[str, Any]:
        """Summary statistics of the program registry."""
        if not os.path.exists(self._path):
            return {"total": 0}
        count = 0
        certified = 0
        derivations: Dict[str, int] = {}
        with open(self._path, "r") as f:
            for line in f:
                try:
                    entry = json.loads(line.strip())
                    count += 1
                    if entry.get("outcome_certified"):
                        certified += 1
                    dt = entry.get("derivation", "unknown")
                    derivations[dt] = derivations.get(dt, 0) + 1
                except (json.JSONDecodeError, ValueError):
                    continue
        return {
            "total": count,
            "certified": certified,
            "derivations": derivations,
        }
