"""Deploy Handoff: certificate → servable artifact + scoring entrypoint.

The certificate currently stops at "certified champion with a sealed lower bound."  This module
closes the loop to a usable artifact: given a GoalCertificate (or GoalLoopResult), it emits:

  1. A serialized model artifact (.joblib or .pt) loadable without the research framework
  2. A self-contained scoring entrypoint (predict.py) that takes raw input → predictions
  3. A manifest.json with metadata (family, params, sealed_lb, threshold, metric, provenance)
  4. Optionally: a Docker-ready directory that `docker build && docker run` serves the model

The frozen core is NOT referenced at inference time -- the certificate was the rigor gate; the
deployed artifact is just a model + a predict function. No statistical guarantees are claimed at
serving time beyond what the certificate already sealed.

Usage:
    from vfplatform.deploy import package_artifact
    artifact = package_artifact(certificate, estimator, output_dir="/path/to/deploy")
    # -> writes model.joblib, predict.py, manifest.json, Dockerfile

The estimator comes from the loop's `estimators[winner.run_id]` dict (the fitted sklearn/torch
object that produced the winning predictions). If unavailable (remote-only run), the manifest
records "estimator_available=False" and the user must refit (the params + family are in the manifest).
"""
from __future__ import annotations

import json
import os
import textwrap
from dataclasses import asdict, dataclass, field
from typing import Optional


@dataclass
class DeployArtifact:
    """Metadata for a deployed model artifact."""
    output_dir: str
    model_path: str                    # path to .joblib or .pt
    predict_script: str                # path to predict.py
    manifest_path: str                 # path to manifest.json
    dockerfile_path: Optional[str]     # path to Dockerfile (if docker=True)
    family: str
    params: dict
    sealed_lb: float
    threshold: float
    metric: str
    estimator_available: bool


@dataclass
class DeployManifest:
    """Machine-readable deployment manifest."""
    family: str
    params: dict
    metric: str
    threshold: float
    sealed_lower_bound: float
    sealed_accuracy: dict
    n_test: int
    task_type: str
    n_classes: int
    n_features: int
    model_file: str                    # relative path to the model file
    predict_script: str                # relative path to predict.py
    estimator_available: bool
    provenance: dict = field(default_factory=dict)
    created_at: str = ""


def _serialize_estimator(estimator, output_dir: str, family: str) -> tuple:
    """Serialize the fitted estimator to disk. Returns (filename, format)."""
    os.makedirs(output_dir, exist_ok=True)

    # torch models: save state_dict
    is_torch = False
    try:
        import torch
        if hasattr(estimator, "state_dict") or hasattr(estimator, "model_"):
            is_torch = True
    except ImportError:
        pass

    if is_torch:
        import torch
        path = os.path.join(output_dir, "model.pt")
        model_obj = getattr(estimator, "model_", estimator)
        torch.save(model_obj.state_dict(), path)
        return "model.pt", "torch"

    # sklearn / joblib path
    try:
        import joblib
        path = os.path.join(output_dir, "model.joblib")
        joblib.dump(estimator, path)
        return "model.joblib", "joblib"
    except ImportError:
        # fallback to pickle
        import pickle
        path = os.path.join(output_dir, "model.pkl")
        with open(path, "wb") as f:
            pickle.dump(estimator, f)
        return "model.pkl", "pickle"


def _generate_predict_script(family: str, params: dict, model_file: str, fmt: str,
                             task_type: str, n_features: int, n_classes: int) -> str:
    """Generate a self-contained predict.py that loads the model and scores new data."""
    return textwrap.dedent(f'''\
        """Scoring entrypoint for the certified champion: {family}
        Generated by Attestra deploy handoff. The model was certified with a sealed
        Clopper-Pearson lower bound -- no further statistical claims are made at serving time.

        Usage:
            python predict.py input.csv          # prints predictions to stdout
            python predict.py input.csv -o out.csv  # writes predictions to file

        Or as a library:
            from predict import load_model, predict
            model = load_model()
            predictions = predict(model, X)  # X is a numpy array (n_samples, {n_features})
        """
        import os
        import sys
        import numpy as np

        MODEL_FILE = "{model_file}"
        MODEL_FORMAT = "{fmt}"
        FAMILY = "{family}"
        TASK_TYPE = "{task_type}"
        N_FEATURES = {n_features}
        N_CLASSES = {n_classes}


        def load_model(model_dir=None):
            """Load the serialized model from disk."""
            if model_dir is None:
                model_dir = os.path.dirname(os.path.abspath(__file__))
            path = os.path.join(model_dir, MODEL_FILE)

            if MODEL_FORMAT == "joblib":
                import joblib
                return joblib.load(path)
            elif MODEL_FORMAT == "pickle":
                import pickle
                with open(path, "rb") as f:
                    return pickle.load(f)
            elif MODEL_FORMAT == "torch":
                import torch
                state = torch.load(path, map_location="cpu")
                # Note: for torch models, you need to reconstruct the architecture
                # and load the state dict. Family: {family}, params: {params}
                raise NotImplementedError(
                    "Torch model loading requires architecture reconstruction. "
                    "See manifest.json for family/params to rebuild the model."
                )
            else:
                raise ValueError(f"Unknown model format: {{MODEL_FORMAT}}")


        def predict(model, X):
            """Run predictions on input array X (shape: n_samples x {n_features})."""
            X = np.asarray(X, dtype=np.float64)
            if X.ndim == 1:
                X = X.reshape(1, -1)
            return model.predict(X)


        def predict_proba(model, X):
            """Run probability predictions (classification only)."""
            X = np.asarray(X, dtype=np.float64)
            if X.ndim == 1:
                X = X.reshape(1, -1)
            if hasattr(model, "predict_proba"):
                return model.predict_proba(X)
            return None


        def main():
            import argparse
            parser = argparse.ArgumentParser(description="Score new data with the certified champion.")
            parser.add_argument("input", help="Path to input CSV (must have {n_features} numeric columns)")
            parser.add_argument("-o", "--output", help="Output CSV path (default: stdout)")
            args = parser.parse_args()

            import pandas as pd
            df = pd.read_csv(args.input)
            X = df.select_dtypes(include=[np.number]).to_numpy(dtype=np.float64)
            if X.shape[1] != N_FEATURES:
                print(f"Warning: expected {{N_FEATURES}} features, got {{X.shape[1]}}", file=sys.stderr)

            model = load_model()
            preds = predict(model, X)

            if args.output:
                pd.DataFrame({{"prediction": preds}}).to_csv(args.output, index=False)
                print(f"Predictions written to {{args.output}}")
            else:
                for p in preds:
                    print(p)


        if __name__ == "__main__":
            main()
    ''')


def _generate_dockerfile(model_file: str, fmt: str) -> str:
    """Generate a minimal Dockerfile for serving the model."""
    deps = "numpy pandas"
    if fmt == "joblib":
        deps += " scikit-learn joblib"
    elif fmt == "torch":
        deps += " torch"

    return textwrap.dedent(f'''\
        FROM python:3.11-slim
        WORKDIR /app
        COPY . /app/
        RUN pip install --no-cache-dir {deps}
        EXPOSE 8080
        CMD ["python", "predict.py"]
    ''')


def package_artifact(certificate, estimator=None, *, output_dir: str,
                     docker: bool = True, n_features: int = 0, n_classes: int = 0) -> DeployArtifact:
    """Package a certified champion into a deployable artifact directory.

    Args:
        certificate: a GoalCertificate or dict with the certification results
        estimator: the fitted sklearn/torch estimator (None if remote-only)
        output_dir: directory to write the artifact to
        docker: whether to generate a Dockerfile
        n_features: number of input features
        n_classes: number of classes (0 for regression)
    """
    os.makedirs(output_dir, exist_ok=True)

    # extract certificate fields
    if hasattr(certificate, "to_dict"):
        cert = certificate.to_dict()
    elif isinstance(certificate, dict):
        cert = certificate
    else:
        cert = {}

    family = cert.get("champion", "unknown")
    params = cert.get("champion_recipe", {})
    sealed_lb = float(cert.get("pooled_sealed_lb", 0.0))
    threshold = float(cert.get("theta_floor", 0.5))
    metric = (cert.get("spec") or {}).get("metric", "accuracy")
    task_type = (cert.get("spec") or {}).get("task_type", "binary")
    sealed_acc = cert.get("sealed_acc", {})
    n_test = int((cert.get("spec") or {}).get("n_rows", 0))

    # serialize the estimator
    estimator_available = estimator is not None
    model_file, fmt = ("model.joblib", "joblib")
    if estimator is not None:
        model_file, fmt = _serialize_estimator(estimator, output_dir, family)
    else:
        # write a placeholder noting the model must be refit
        with open(os.path.join(output_dir, "REFIT_REQUIRED.txt"), "w") as f:
            f.write(f"The estimator was not available at deploy time (remote-only run).\n"
                    f"To reconstruct: family={family}, params={json.dumps(params)}\n"
                    f"Use the catalog entry to rebuild: harness.catalog()['{family}'].build(params, seed=0)\n")

    # generate predict.py
    predict_code = _generate_predict_script(family, params, model_file, fmt,
                                            task_type, n_features, n_classes)
    predict_path = os.path.join(output_dir, "predict.py")
    with open(predict_path, "w") as f:
        f.write(predict_code)

    # write manifest.json
    import datetime
    manifest = DeployManifest(
        family=family, params=params, metric=metric, threshold=threshold,
        sealed_lower_bound=sealed_lb, sealed_accuracy=sealed_acc,
        n_test=n_test, task_type=task_type, n_classes=n_classes, n_features=n_features,
        model_file=model_file, predict_script="predict.py",
        estimator_available=estimator_available,
        provenance=cert.get("literature", {}),
        created_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),
    )
    manifest_path = os.path.join(output_dir, "manifest.json")
    with open(manifest_path, "w") as f:
        json.dump(asdict(manifest), f, indent=2, default=str)

    # Dockerfile
    dockerfile_path = None
    if docker:
        dockerfile_path = os.path.join(output_dir, "Dockerfile")
        with open(dockerfile_path, "w") as f:
            f.write(_generate_dockerfile(model_file, fmt))

    return DeployArtifact(
        output_dir=output_dir, model_path=os.path.join(output_dir, model_file),
        predict_script=predict_path, manifest_path=manifest_path,
        dockerfile_path=dockerfile_path, family=family, params=params,
        sealed_lb=sealed_lb, threshold=threshold, metric=metric,
        estimator_available=estimator_available,
    )


def summary(artifact: DeployArtifact) -> dict:
    """Human-readable summary of the deployed artifact."""
    return {
        "output_dir": artifact.output_dir,
        "model": artifact.model_path,
        "predict_script": artifact.predict_script,
        "family": artifact.family,
        "sealed_lb": artifact.sealed_lb,
        "threshold": artifact.threshold,
        "metric": artifact.metric,
        "estimator_available": artifact.estimator_available,
        "files": [f for f in os.listdir(artifact.output_dir)
                  if os.path.isfile(os.path.join(artifact.output_dir, f))],
    }
